[0m09:23:05.872294 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9738A1BE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E976364C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E976364E50>]}


============================== 09:23:05.934787 | 57d0bebb-01dc-47d9-805d-af37a9fc6c4d ==============================
[0m09:23:05.934787 [info ] [MainThread]: Running with dbt=1.8.6
[0m09:23:05.934787 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init superside_hr', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:23:06.744925 [debug] [MainThread]: Starter project path: C:\Users\hp\anaconda3\lib\site-packages\dbt\include\starter_project
[0m09:23:06.899964 [info ] [MainThread]: 
Your new dbt project "superside_hr" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:23:06.903980 [info ] [MainThread]: Setting up your profile.
[0m10:11:24.721392 [info ] [MainThread]: Profile superside_hr written to C:\Users\hp\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m10:11:24.741135 [debug] [MainThread]: Command `dbt init` succeeded at 10:11:24.740253 after 2899.01 seconds
[0m10:11:24.743135 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E9738A1BE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E976339130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E976328A30>]}
[0m10:11:24.746674 [debug] [MainThread]: Flushing usage events
[0m10:11:47.301985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD07431C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD07DB93D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD070F5E50>]}


============================== 10:11:47.301985 | 380b65ae-6a13-477e-9c53-32286d7c2332 ==============================
[0m10:11:47.301985 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:11:47.301985 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:11:47.463035 [info ] [MainThread]: dbt version: 1.8.6
[0m10:11:47.465034 [info ] [MainThread]: python version: 3.9.19
[0m10:11:47.467035 [info ] [MainThread]: python path: C:\Users\hp\anaconda3\python.exe
[0m10:11:47.468032 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m10:11:50.638163 [info ] [MainThread]: Using profiles dir at C:\Users\hp\.dbt
[0m10:11:50.638163 [info ] [MainThread]: Using profiles.yml file at C:\Users\hp\.dbt\profiles.yml
[0m10:11:50.638163 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\hp\Desktop\Superside_HR_Manager\dbt_project.yml
[0m10:11:50.638163 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m10:11:50.654933 [debug] [MainThread]: Command `dbt debug` failed at 10:11:50.654933 after 3.50 seconds
[0m10:11:50.655934 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD07431C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD09BD5A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AD070F5C10>]}
[0m10:11:50.656932 [debug] [MainThread]: Flushing usage events
[0m11:20:09.108659 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029AA86A1C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029AAB164B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029AAB164D60>]}


============================== 11:20:09.108659 | 440fe69a-7d9f-49fb-a5c5-8bf73340a81e ==============================
[0m11:20:09.108659 [info ] [MainThread]: Running with dbt=1.8.6
[0m11:20:09.108659 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt test', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:20:09.124288 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\Superside_HR_Manager\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:20:09.124288 [debug] [MainThread]: Command `dbt test` failed at 11:20:09.124288 after 0.12 seconds
[0m11:20:09.124288 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029AA86A1C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029AAB164BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029AAB164AC0>]}
[0m11:20:09.124288 [debug] [MainThread]: Flushing usage events
[0m11:21:27.610454 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E33DF01BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3409C03A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3409C0130>]}


============================== 11:21:27.626093 | ec8d90f3-dbf4-442a-b46c-e1ce20380d1c ==============================
[0m11:21:27.626093 [info ] [MainThread]: Running with dbt=1.8.6
[0m11:21:27.626093 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:21:27.626093 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\Superside_HR_Manager\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:21:27.639075 [debug] [MainThread]: Command `dbt run` failed at 11:21:27.639075 after 0.12 seconds
[0m11:21:27.641079 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E33DF01BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E34098A370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E34098A760>]}
[0m11:21:27.642668 [debug] [MainThread]: Flushing usage events
[0m11:27:14.832662 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000185C16F1C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000185C41B5BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000185C41B5D90>]}


============================== 11:27:14.848311 | 65059ccb-49f0-431b-887d-4a5e596faddb ==============================
[0m11:27:14.848311 [info ] [MainThread]: Running with dbt=1.8.6
[0m11:27:14.848311 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt test', 'send_anonymous_usage_stats': 'True'}
[0m11:27:14.848311 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\Superside_HR_Manager\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:27:14.848311 [debug] [MainThread]: Command `dbt test` failed at 11:27:14.848311 after 0.13 seconds
[0m11:27:14.848311 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000185C16F1C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000185C41B5C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000185C41B5B20>]}
[0m11:27:14.848311 [debug] [MainThread]: Flushing usage events
[0m09:09:54.812847 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021344BB1C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021347674B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021347674D60>]}


============================== 09:09:54.844149 | b0a1cd66-91ce-4db5-b252-237e4802f4f6 ==============================
[0m09:09:54.844149 [info ] [MainThread]: Running with dbt=1.8.6
[0m09:09:54.844149 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m09:09:54.844149 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\Superside_HR_Manager\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:09:54.859701 [debug] [MainThread]: Command `dbt run` failed at 09:09:54.859701 after 0.25 seconds
[0m09:09:54.859701 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021344BB1C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021347674BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021347674AC0>]}
[0m09:09:54.859701 [debug] [MainThread]: Flushing usage events
[0m09:29:04.146385 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000204AC621C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000204AF0E6C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000204AF0E6DF0>]}


============================== 09:29:04.146385 | 8249e43c-2b21-458f-800c-1d4251f4cc29 ==============================
[0m09:29:04.146385 [info ] [MainThread]: Running with dbt=1.8.6
[0m09:29:04.162009 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:29:04.162009 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\Superside_HR_Manager\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:29:04.170805 [debug] [MainThread]: Command `dbt run` failed at 09:29:04.170805 after 0.25 seconds
[0m09:29:04.172808 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000204AC621C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000204AF0E6C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000204AF0E6B80>]}
[0m09:29:04.174840 [debug] [MainThread]: Flushing usage events
[0m15:50:59.319603 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFA2D21C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFA57E0460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFA57E0130>]}


============================== 15:50:59.397700 | cf3a62d1-3d0d-4c24-a612-6222bacf01d0 ==============================
[0m15:50:59.397700 [info ] [MainThread]: Running with dbt=1.8.6
[0m15:50:59.397700 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:50:59.397700 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\Desktop\Superside_HR_Manager\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:50:59.397700 [debug] [MainThread]: Command `dbt deps` failed at 15:50:59.397700 after 0.29 seconds
[0m15:50:59.413348 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFA2D21C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFA57BD9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BFA57BD970>]}
[0m15:50:59.414798 [debug] [MainThread]: Flushing usage events
